.\" gtk-knocker man page
.\" Process this file with: groff -man -Tascii
.\" man page originally written by  Gabriele Giorgetti <g.gabriele79@genie.it>
.TH GTK-KNOCKER 1 "March 31, 2002"
.SH NAME
gtk-knocker \- A easy to use GTK+ network security port scanner
.SH SYNOPSIS
.B \fBgtk-knocker\fR
[\fIOPTION\fR]
.SH DESCRIPTION
.B gtk-knocker 
is a simple and easy to use TCP security port scanner
which is able to analyze hosts and all of the different services started on
them.
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
display this help and exit
.TP
\fB\-v\fR, \fB\-\-version\fR
output version information and exit
.SH EXAMPLES
.LP
To run this program the standard way type:
.LP
gtk-knocker
.SH AVAILABILTY   
The latest version of this program can be found at
http://knocker.sourceforge.net
.SH BUGS
See the BUGS file in the gtk-knocker source package for a list of known bugs.
Report bugs to <g.gabriele79@genie.it>
.SH AUTHOR
gtk-knocker is written by Gabriele Giorgetti <g.gabriele79@genie.it>
.PP
This manual page is written by Gabriele Giorgetti 
<g.gabriele79@genie.it>.
.SH COPYRIGHT
Copyright \(co 2001 Gabriele Giorgetti
.br
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
