/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "gtk_callbacks.h"
#include "gtk_interface.h"
#include "gtk_support.h"

GtkWidget*
create_main_window (void)
{
  GtkWidget *main_window;
  GtkWidget *main_window_table;
  GtkWidget *menu_handlebox;
  GtkWidget *menubar;
  guint tmp_key;
  GtkWidget *file_menubar;
  GtkWidget *file_menubar_menu;
  GtkAccelGroup *file_menubar_menu_accels;
  GtkWidget *file_quit_menubar;
  GtkWidget *settings_menubar;
  GtkWidget *settings_menubar_menu;
  GtkAccelGroup *settings_menubar_menu_accels;
  GtkWidget *noneyet;
  GtkWidget *help_menubar;
  GtkWidget *help_menubar_menu;
  GtkAccelGroup *help_menubar_menu_accels;
  GtkWidget *help_about_menubar;
  GtkWidget *options_handlebox;
  GtkWidget *options_table;
  GtkWidget *host_combobox;
  GtkWidget *host_entry;
  GtkWidget *end_scan_button;
  GtkWidget *logfile_checkbutton;
  GtkObject *start_port_n_spinbutton_adj;
  GtkWidget *start_port_n_spinbutton;
  GtkObject *stop_port_n_spinbutton_adj;
  GtkWidget *stop_port_n_spinbutton;
  GtkWidget *logfile_entry;
  GtkWidget *start_scan_button;
  GtkWidget *bottom_bar_table;
  GtkWidget *close_button;
  GtkWidget *main_statusbar;
  GtkWidget *scan_progressbar;
  GtkWidget *text_scrolledwindow;
  GtkWidget *text_output_view;
  GtkWidget *clist_scrolledwindow;
  GtkWidget *results_clist;
  GtkWidget *hostip_label;
  GtkWidget *open_port_label;
  GtkWidget *service_label;
  GtkAccelGroup *accel_group;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  accel_group = gtk_accel_group_new ();

  main_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (main_window), "main_window", main_window);
  gtk_window_set_title (GTK_WINDOW (main_window), "APPLICATION_NAME");
  gtk_window_set_position (GTK_WINDOW (main_window), GTK_WIN_POS_CENTER);

  main_window_table = gtk_table_new (5, 1, FALSE);
  gtk_widget_ref (main_window_table);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "main_window_table", main_window_table,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_window_table);
  gtk_container_add (GTK_CONTAINER (main_window), main_window_table);

  menu_handlebox = gtk_handle_box_new ();
  gtk_widget_ref (menu_handlebox);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "menu_handlebox", menu_handlebox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menu_handlebox);
  gtk_table_attach (GTK_TABLE (main_window_table), menu_handlebox, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  menubar = gtk_menu_bar_new ();
  gtk_widget_ref (menubar);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "menubar", menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (menubar);
  gtk_container_add (GTK_CONTAINER (menu_handlebox), menubar);

  file_menubar = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file_menubar)->child),
                                   "_File");
  gtk_widget_add_accelerator (file_menubar, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (file_menubar);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "file_menubar", file_menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file_menubar);
  gtk_container_add (GTK_CONTAINER (menubar), file_menubar);

  file_menubar_menu = gtk_menu_new ();
  gtk_widget_ref (file_menubar_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "file_menubar_menu", file_menubar_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (file_menubar), file_menubar_menu);
  file_menubar_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (file_menubar_menu));

  file_quit_menubar = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (file_quit_menubar)->child),
                                   "_Quit");
  gtk_widget_add_accelerator (file_quit_menubar, "activate_item", file_menubar_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (file_quit_menubar);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "file_quit_menubar", file_quit_menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (file_quit_menubar);
  gtk_container_add (GTK_CONTAINER (file_menubar_menu), file_quit_menubar);
  gtk_widget_add_accelerator (file_quit_menubar, "activate", accel_group,
                              GDK_Q, GDK_CONTROL_MASK,
                              GTK_ACCEL_VISIBLE);

  settings_menubar = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (settings_menubar)->child),
                                   "_Settings");
  gtk_widget_add_accelerator (settings_menubar, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (settings_menubar);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "settings_menubar", settings_menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (settings_menubar);
  gtk_container_add (GTK_CONTAINER (menubar), settings_menubar);

  settings_menubar_menu = gtk_menu_new ();
  gtk_widget_ref (settings_menubar_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "settings_menubar_menu", settings_menubar_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (settings_menubar), settings_menubar_menu);
  settings_menubar_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (settings_menubar_menu));

  noneyet = gtk_menu_item_new_with_label ("NONE YET");
  gtk_widget_ref (noneyet);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "noneyet", noneyet,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (noneyet);
  gtk_container_add (GTK_CONTAINER (settings_menubar_menu), noneyet);

  help_menubar = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help_menubar)->child),
                                   "_Help");
  gtk_widget_add_accelerator (help_menubar, "activate_item", accel_group,
                              tmp_key, GDK_MOD1_MASK, (GtkAccelFlags) 0);
  gtk_widget_ref (help_menubar);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "help_menubar", help_menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help_menubar);
  gtk_container_add (GTK_CONTAINER (menubar), help_menubar);
  gtk_menu_item_right_justify (GTK_MENU_ITEM (help_menubar));

  help_menubar_menu = gtk_menu_new ();
  gtk_widget_ref (help_menubar_menu);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "help_menubar_menu", help_menubar_menu,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_menu_item_set_submenu (GTK_MENU_ITEM (help_menubar), help_menubar_menu);
  help_menubar_menu_accels = gtk_menu_ensure_uline_accel_group (GTK_MENU (help_menubar_menu));

  help_about_menubar = gtk_menu_item_new_with_label ("");
  tmp_key = gtk_label_parse_uline (GTK_LABEL (GTK_BIN (help_about_menubar)->child),
                                   "_About...");
  gtk_widget_add_accelerator (help_about_menubar, "activate_item", help_menubar_menu_accels,
                              tmp_key, 0, 0);
  gtk_widget_ref (help_about_menubar);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "help_about_menubar", help_about_menubar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (help_about_menubar);
  gtk_container_add (GTK_CONTAINER (help_menubar_menu), help_about_menubar);

  options_handlebox = gtk_handle_box_new ();
  gtk_widget_ref (options_handlebox);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "options_handlebox", options_handlebox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (options_handlebox);
  gtk_table_attach (GTK_TABLE (main_window_table), options_handlebox, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  options_table = gtk_table_new (2, 5, FALSE);
  gtk_widget_ref (options_table);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "options_table", options_table,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (options_table);
  gtk_container_add (GTK_CONTAINER (options_handlebox), options_table);
  gtk_container_set_border_width (GTK_CONTAINER (options_table), 2);

  host_combobox = gtk_combo_new ();
  gtk_widget_ref (host_combobox);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "host_combobox", host_combobox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (host_combobox);
  gtk_table_attach (GTK_TABLE (options_table), host_combobox, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (host_combobox), 2);
  gtk_combo_set_case_sensitive (GTK_COMBO (host_combobox), TRUE);

  host_entry = GTK_COMBO (host_combobox)->entry;
  gtk_widget_ref (host_entry);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "host_entry", host_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (host_entry);
  gtk_entry_set_text (GTK_ENTRY (host_entry), "127.0.0.1");

  end_scan_button = gtk_button_new_with_label (" stop the scan ");
  gtk_widget_ref (end_scan_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "end_scan_button", end_scan_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (end_scan_button);
  gtk_table_attach (GTK_TABLE (options_table), end_scan_button, 4, 5, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (end_scan_button), 2);

  logfile_checkbutton = gtk_check_button_new_with_label ("Log to file");
  gtk_widget_ref (logfile_checkbutton);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "logfile_checkbutton", logfile_checkbutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (logfile_checkbutton);
  gtk_table_attach (GTK_TABLE (options_table), logfile_checkbutton, 4, 5, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (logfile_checkbutton), 2);

  start_port_n_spinbutton_adj = gtk_adjustment_new (1, 1, 65000, 1, 10, 10);
  start_port_n_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (start_port_n_spinbutton_adj), 1, 0);
  gtk_widget_ref (start_port_n_spinbutton);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "start_port_n_spinbutton", start_port_n_spinbutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (start_port_n_spinbutton);
  gtk_table_attach (GTK_TABLE (options_table), start_port_n_spinbutton, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 2, 2);
  gtk_tooltips_set_tip (tooltips, start_port_n_spinbutton, "Port number to begin the scan from", NULL);

  stop_port_n_spinbutton_adj = gtk_adjustment_new (1023, 1, 65000, 1, 10, 10);
  stop_port_n_spinbutton = gtk_spin_button_new (GTK_ADJUSTMENT (stop_port_n_spinbutton_adj), 1, 0);
  gtk_widget_ref (stop_port_n_spinbutton);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "stop_port_n_spinbutton", stop_port_n_spinbutton,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (stop_port_n_spinbutton);
  gtk_table_attach (GTK_TABLE (options_table), stop_port_n_spinbutton, 2, 3, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 2, 2);
  gtk_tooltips_set_tip (tooltips, stop_port_n_spinbutton, "POrtt number to end the scan to", NULL);

  logfile_entry = gtk_entry_new ();
  gtk_widget_ref (logfile_entry);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "logfile_entry", logfile_entry,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (logfile_entry);
  gtk_table_attach (GTK_TABLE (options_table), logfile_entry, 0, 4, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 2, 2);
  gtk_tooltips_set_tip (tooltips, logfile_entry, "the path to the log file if logging is enabled", NULL);

  start_scan_button = gtk_button_new_with_label (" start the scan ");
  gtk_widget_ref (start_scan_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "start_scan_button", start_scan_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (start_scan_button);
  gtk_table_attach (GTK_TABLE (options_table), start_scan_button, 3, 4, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (start_scan_button), 2);

  bottom_bar_table = gtk_table_new (1, 3, FALSE);
  gtk_widget_ref (bottom_bar_table);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "bottom_bar_table", bottom_bar_table,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bottom_bar_table);
  gtk_table_attach (GTK_TABLE (main_window_table), bottom_bar_table, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_SHRINK), 0, 0);

  close_button = gtk_button_new_with_label (" Close ");
  gtk_widget_ref (close_button);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "close_button", close_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (close_button);
  gtk_table_attach (GTK_TABLE (bottom_bar_table), close_button, 2, 3, 0, 1,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (close_button), 2);

  main_statusbar = gtk_statusbar_new ();
  gtk_widget_ref (main_statusbar);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "main_statusbar", main_statusbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_statusbar);
  gtk_table_attach (GTK_TABLE (bottom_bar_table), main_statusbar, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  scan_progressbar = gtk_progress_bar_new ();
  gtk_widget_ref (scan_progressbar);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "scan_progressbar", scan_progressbar,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (scan_progressbar);
  gtk_table_attach (GTK_TABLE (bottom_bar_table), scan_progressbar, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  text_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (text_scrolledwindow);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "text_scrolledwindow", text_scrolledwindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text_scrolledwindow);
  gtk_table_attach (GTK_TABLE (main_window_table), text_scrolledwindow, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (text_scrolledwindow), 6);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (text_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  text_output_view = gtk_text_new (NULL, NULL);
  gtk_widget_ref (text_output_view);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "text_output_view", text_output_view,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text_output_view);
  gtk_container_add (GTK_CONTAINER (text_scrolledwindow), text_output_view);

  clist_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (clist_scrolledwindow);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "clist_scrolledwindow", clist_scrolledwindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (clist_scrolledwindow);
  gtk_table_attach (GTK_TABLE (main_window_table), clist_scrolledwindow, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (clist_scrolledwindow), 6);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (clist_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  results_clist = gtk_clist_new (3);
  gtk_widget_ref (results_clist);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "results_clist", results_clist,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (results_clist);
  gtk_container_add (GTK_CONTAINER (clist_scrolledwindow), results_clist);
  gtk_clist_set_column_width (GTK_CLIST (results_clist), 0, 137);
  gtk_clist_set_column_width (GTK_CLIST (results_clist), 1, 109);
  gtk_clist_set_column_width (GTK_CLIST (results_clist), 2, 136);
  gtk_clist_column_titles_show (GTK_CLIST (results_clist));

  hostip_label = gtk_label_new ("Host IP:");
  gtk_widget_ref (hostip_label);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "hostip_label", hostip_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (hostip_label);
  gtk_clist_set_column_widget (GTK_CLIST (results_clist), 0, hostip_label);

  open_port_label = gtk_label_new ("Open Port:");
  gtk_widget_ref (open_port_label);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "open_port_label", open_port_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (open_port_label);
  gtk_clist_set_column_widget (GTK_CLIST (results_clist), 1, open_port_label);

  service_label = gtk_label_new ("Service:");
  gtk_widget_ref (service_label);
  gtk_object_set_data_full (GTK_OBJECT (main_window), "service_label", service_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (service_label);
  gtk_clist_set_column_widget (GTK_CLIST (results_clist), 2, service_label);

  gtk_signal_connect_object (GTK_OBJECT (main_window), "delete_event",
                             GTK_SIGNAL_FUNC (on_main_window_delete_event),
                             GTK_OBJECT (main_window));
  gtk_signal_connect (GTK_OBJECT (file_quit_menubar), "activate",
                      GTK_SIGNAL_FUNC (on_menubar_file_quit_activate),
                      NULL);
  gtk_signal_connect (GTK_OBJECT (help_about_menubar), "activate",
                      GTK_SIGNAL_FUNC (on_help_about_menubar_activate),
                      NULL);
  gtk_signal_connect_object (GTK_OBJECT (end_scan_button), "clicked",
                             GTK_SIGNAL_FUNC (on_button_stop_the_scan_clicked),
                             GTK_OBJECT (main_window));
  gtk_signal_connect_object (GTK_OBJECT (start_scan_button), "clicked",
                             GTK_SIGNAL_FUNC (on_button_start_the_scan_clicked),
                             GTK_OBJECT (main_window));
  gtk_signal_connect_object (GTK_OBJECT (close_button), "clicked",
                             GTK_SIGNAL_FUNC (on_close_button_clicked),
                             GTK_OBJECT (main_window));

  gtk_object_set_data (GTK_OBJECT (main_window), "tooltips", tooltips);

  gtk_window_add_accel_group (GTK_WINDOW (main_window), accel_group);

  return main_window;
}

GtkWidget*
create_about_window (void)
{
  GtkWidget *about_window;
  GtkWidget *main_table;
  GtkWidget *bottom_hbuttonbox;
  GtkWidget *close_button;
  GtkWidget *main_notebook;
  GtkWidget *notebook_table;
  GtkWidget *title_version_label;
  GtkWidget *labels_table;
  GtkWidget *homepage_label;
  GtkWidget *copyright_label;
  GtkWidget *gtpl_license_label;
  GtkWidget *knocker_logo_pixmap;
  GtkWidget *about_label;
  GtkWidget *text_scrolledwindow;
  GtkWidget *license_text;
  GtkWidget *license_label;
  GtkWidget *bottom_hseparator;

  about_window = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_object_set_data (GTK_OBJECT (about_window), "about_window", about_window);
  gtk_container_set_border_width (GTK_CONTAINER (about_window), 10);
  gtk_window_set_title (GTK_WINDOW (about_window), "About gtk-knocker");
  gtk_window_set_position (GTK_WINDOW (about_window), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (about_window), 510, 400);

  main_table = gtk_table_new (3, 1, FALSE);
  gtk_widget_ref (main_table);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "main_table", main_table,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_table);
  gtk_container_add (GTK_CONTAINER (about_window), main_table);

  bottom_hbuttonbox = gtk_hbutton_box_new ();
  gtk_widget_ref (bottom_hbuttonbox);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "bottom_hbuttonbox", bottom_hbuttonbox,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bottom_hbuttonbox);
  gtk_table_attach (GTK_TABLE (main_table), bottom_hbuttonbox, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_SHRINK), 0, 0);

  close_button = gtk_button_new_with_label ("   Close   ");
  gtk_widget_ref (close_button);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "close_button", close_button,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (close_button);
  gtk_container_add (GTK_CONTAINER (bottom_hbuttonbox), close_button);
  gtk_container_set_border_width (GTK_CONTAINER (close_button), 2);
  GTK_WIDGET_SET_FLAGS (close_button, GTK_CAN_DEFAULT);

  main_notebook = gtk_notebook_new ();
  gtk_widget_ref (main_notebook);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "main_notebook", main_notebook,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (main_notebook);
  gtk_table_attach (GTK_TABLE (main_table), main_notebook, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL), 0, 0);
  gtk_container_set_border_width (GTK_CONTAINER (main_notebook), 10);
  gtk_notebook_set_scrollable (GTK_NOTEBOOK (main_notebook), TRUE);

  notebook_table = gtk_table_new (3, 1, FALSE);
  gtk_widget_ref (notebook_table);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "notebook_table", notebook_table,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (notebook_table);
  gtk_container_add (GTK_CONTAINER (main_notebook), notebook_table);

  title_version_label = gtk_label_new ("g t k - k n o c k e r  0 . 6 . 6");
  gtk_widget_ref (title_version_label);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "title_version_label", title_version_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (title_version_label);
  gtk_table_attach (GTK_TABLE (notebook_table), title_version_label, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (title_version_label), 0, 0.5);

  labels_table = gtk_table_new (3, 1, FALSE);
  gtk_widget_ref (labels_table);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "labels_table", labels_table,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (labels_table);
  gtk_table_attach (GTK_TABLE (notebook_table), labels_table, 0, 1, 2, 3,
                    (GtkAttachOptions) (0),
                    (GtkAttachOptions) (GTK_EXPAND), 0, 0);

  homepage_label = gtk_label_new ("Official Home Page: http://knocker.sourceforge.net");
  gtk_widget_ref (homepage_label);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "homepage_label", homepage_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (homepage_label);
  gtk_table_attach (GTK_TABLE (labels_table), homepage_label, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_misc_set_alignment (GTK_MISC (homepage_label), 0, 0.5);

  copyright_label = gtk_label_new ("Copyright (C) 2001,2002 Gabriele Giorgetti <g.gabriele79@genie.it>");
  gtk_widget_ref (copyright_label);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "copyright_label", copyright_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (copyright_label);
  gtk_table_attach (GTK_TABLE (labels_table), copyright_label, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (0), 0, 10);
  gtk_misc_set_alignment (GTK_MISC (copyright_label), 0, 0.5);

  gtpl_license_label = gtk_label_new ("gtk-knocker is licensed under the GNU GPL");
  gtk_widget_ref (gtpl_license_label);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "gtpl_license_label", gtpl_license_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (gtpl_license_label);
  gtk_table_attach (GTK_TABLE (labels_table), gtpl_license_label, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (0), 0, 10);
  gtk_misc_set_alignment (GTK_MISC (gtpl_license_label), 0, 0.5);

  knocker_logo_pixmap = create_pixmap (about_window, "knocker.xpm");
  gtk_widget_ref (knocker_logo_pixmap);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "knocker_logo_pixmap", knocker_logo_pixmap,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (knocker_logo_pixmap);
  gtk_table_attach (GTK_TABLE (notebook_table), knocker_logo_pixmap, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_EXPAND),
                    (GtkAttachOptions) (0), 0, 44);

  about_label = gtk_label_new ("   About   ");
  gtk_widget_ref (about_label);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "about_label", about_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (about_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 0), about_label);

  text_scrolledwindow = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_ref (text_scrolledwindow);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "text_scrolledwindow", text_scrolledwindow,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (text_scrolledwindow);
  gtk_container_add (GTK_CONTAINER (main_notebook), text_scrolledwindow);
  gtk_scrolled_window_set_policy (GTK_SCROLLED_WINDOW (text_scrolledwindow), GTK_POLICY_AUTOMATIC, GTK_POLICY_AUTOMATIC);

  license_text = gtk_text_new (NULL, NULL);
  gtk_widget_ref (license_text);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "license_text", license_text,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (license_text);
  gtk_container_add (GTK_CONTAINER (text_scrolledwindow), license_text);

  license_label = gtk_label_new ("   License Agreement   ");
  gtk_widget_ref (license_label);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "license_label", license_label,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (license_label);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (main_notebook), gtk_notebook_get_nth_page (GTK_NOTEBOOK (main_notebook), 1), license_label);

  bottom_hseparator = gtk_hseparator_new ();
  gtk_widget_ref (bottom_hseparator);
  gtk_object_set_data_full (GTK_OBJECT (about_window), "bottom_hseparator", bottom_hseparator,
                            (GtkDestroyNotify) gtk_widget_unref);
  gtk_widget_show (bottom_hseparator);
  gtk_table_attach (GTK_TABLE (main_table), bottom_hseparator, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_EXPAND | GTK_FILL),
                    (GtkAttachOptions) (GTK_SHRINK), 0, 0);

  gtk_signal_connect_object (GTK_OBJECT (about_window), "delete_event",
                             GTK_SIGNAL_FUNC (on_about_window_delete_event),
                             GTK_OBJECT (about_window));
  gtk_signal_connect_object (GTK_OBJECT (close_button), "clicked",
                             GTK_SIGNAL_FUNC (on_about_window_close_button_clicked),
                             GTK_OBJECT (about_window));

  return about_window;
}

